# Generated by Django 2.0 on 2017-12-22 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('opisanie', models.TextField(
                    max_length=1000, verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Создан')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вопрос\\Ответ',
                'verbose_name_plural': 'Вопросы\\Ответы',
                'ordering': ['title'],
            },
        ),
    ]
