# Generated by Django 2.0.1 on 2018-01-19 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Дата редактирования')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение на форуме',
                'verbose_name_plural': 'Сообщения на форуме',
                'db_table': 'messageforum',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='SectionForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Дата редактирования')),
                ('title', models.CharField(max_length=250, verbose_name='Укажите название раздела на форуме')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'db_table': 'sectionforum',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TopicForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Дата редактирования')),
                ('title', models.CharField(max_length=250, verbose_name='Укажите название темы на форуме')),
                ('text', models.TextField(verbose_name='Текст, описание темы')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_forum', to='sl_forum.SectionForum', verbose_name='Укажите к какому разделу относиться тема')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_forum', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'db_table': 'topicforum',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='UserForum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Дата редактирования')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя пользователя')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Счетчик сообщений пользователя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_forum', to=settings.AUTH_USER_MODEL, verbose_name='Профиль пользователя на форуме')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профиль пользователя',
                'db_table': 'userforum',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='messageforum',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_topic', to='sl_forum.TopicForum', verbose_name='Укажите к какой теме относиться сообщение'),
        ),
        migrations.AddField(
            model_name='messageforum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_forum', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
