# Generated by Django 2.0.1 on 2018-01-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sl_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionforum',
            name='title',
            field=models.CharField(
                max_length=250,
                verbose_name='Укажите название раздела на форуме'),
        ),
        migrations.AlterField(
            model_name='topicforum',
            name='title',
            field=models.CharField(
                max_length=250,
                verbose_name='Укажите название темы на форуме'),
        ),
    ]
